[[verification]]
command = "cargo"
args = ["build", "-p", "ffi_types_that_cant_cross"]

[[verification]]
command = "cheadergen"
args = ["generate", "--lang", "c", "--output-dir", "c_test", "-p", "ffi_types_that_cant_cross"]

[[verification]]
command = "cc"
args = [
  "-Wall",
  "-Wextra",
  "-std=c11",
  "-I.",
  "c_test/test_tag_describe.c",
  "../../../target/debug/libffi_types_that_cant_cross.a",
  "-o",
  "../../../target/debug/test_tag_describe",
]

[[verification]]
command = "../../../target/debug/test_tag_describe"
