/*
 * The C-visible surface of this crate, written by hand on purpose.
 *
 * This is not generated by `cheadergen`: it is the contract the C side of the
 * bookmark manager already relies on. `wr` links the harness next door against
 * the staticlib, so these names are checked by the linker. Renaming the Rust
 * function without giving it an `export_name` that preserves the C name is then
 * a link error rather than a silent ABI break.
 */

#pragma once

void BMNormalizeURL(void);

/* Hands back the buffer it was given. */
unsigned char *copy_bytes(unsigned char *bytes);
