[[verification]]
command = "cargo"
args = ["build"]

[[verification]]
command = "cc"
args = [
  "-Wall",
  "-Wextra",
  "-std=c11",
  "-I.",
  "c_test/test_strlower.c",
  "../../../target/debug/libbm_cheadergen.a",
  "-o",
  "../../../target/debug/test_strlower",
]

[[verification]]
command = "../../../target/debug/test_strlower"
