fn add(a: i32, b: i32) -> i32 {
    // include the bindings generated by `build.rs` (see `OUT_DIR`)
    // then call `bm_add` from them here to implement the add!

    todo!()
}

#[cfg(test)]
mod tests {
    use super::add;

    #[test]
    fn test_add() {
        assert_eq!(add(2, 3), 5);
        assert_eq!(add(0, 0), 0);
    }
}
