mod sys {
    // TODO: include the bindings generated by `build.rs` (see `OUT_DIR`)
    // to make `bm_add` visible to the tests below.
}

#[cfg(test)]
mod tests {
    use super::sys::bm_add;

    #[test]
    fn test_add() {
        assert_eq!(unsafe { bm_add(2, 3) }, 5);
        assert_eq!(unsafe { bm_add(0, 0) }, 0);
    }
}
